# Generated by Django 2.1.4 on 2018-12-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.NullBooleanField(),
        ),
    ]
