# Generated by Django 2.1.4 on 2018-12-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_usersinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersInfo',
        ),
    ]
